### ISSUE TITLE
Electron-statusbar library not working

### ISSUE THREAD

**Issue by mazeeblanke** [Floffah/electron-statusbar#2]
i tried to use this package, by importing it as specified in the docs, but what i get is an empty object.

`const es = require("electron-statusbar")`

Since 'es' is an empty object, i get errors that the methods cannot be found :(

**Comment by Floffah** [comment]
I am currently re-coding this library. It will work soon. When I originally created this I wasn't very good at node.js... but with the knowledge I have now, I am going to re-code it. (BTW make sure you are running this inside html files.)

**Comment by mazeeblanke** [comment]
okay great
